/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2014-04-16 16:18:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;
import java.util.Enumeration;
import java.util.Map;
import java.util.Iterator;
import majorserver.IndexServer;

public final class symptoms_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./cssimages/style.css\" />\n");
      out.write("<script src=\"./cssimages/jquery-1.11.0.min.js\"></script>\n");
      out.write("<script src=\"./cssimages/select2.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"./cssimages/select2.css\">\n");
      out.write("\n");
      out.write("<title>Health Diagnosing System</title>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("$(document).ready(function() { $(\"#words\").select2({\n");
      out.write("\t\t\t maximumSelectionSize: 5,\n");
      out.write("\t\t\t allowClear: true,\n");
      out.write("\t\t\t placeholder: \"Type a word\"\n");
      out.write("\t\t\t}); \n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("    <div id=\"page\">\n");
      out.write("\t\t\n");
      out.write("        <div id=\"header\">\n");
      out.write("        \t<h1>Health Diagnosing System</h1>\n");
      out.write("            <h2>Ask your online doctor</h2>\n");
      out.write("            \n");
      out.write("\t      </div>\n");
      out.write("\t\t<div id=\"bar\">\n");
      out.write("\t\t    <ul>\n");
      out.write("\t\t        <li><a href=\"./index.html\">Home</a></li>\n");
      out.write("\t\t        <li><a href=\"#\">Diagnosing system</a></li>\n");
      out.write("\t\t        <li><a href=\"./index.html\">Contact</a></li>\n");
      out.write("\t\t    </ul>\n");
      out.write("\t      </div>\n");
      out.write("\t\t<div class=\"contentTitle\"><h1>Symptom checker</h1></div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"contentText\" name=\"contentText\" id=\"contentText\">\n");
      out.write("\t\t  <h4>Please enter the symptoms you are facing:</h4>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<img src=\"./cssimages/A-Picture-Of-A-Human-Body.jpg\" alt=\"HumanBody\" usemap=\"#human\">\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\t\t<div id=\"symptoms\" style=\"height:600px;width:400px;float:right;\">\n");
      out.write("                    <form action=\"result.jsp\" method=\"post\">\n");
      out.write("                        <p> Selected body parts </p>\n");
      out.write("                        ");
 
                            StringBuilder bplist=new StringBuilder();
                            String bodypartslist[]=request.getParameterValues("bodyparts");
                            for(String bp:bodypartslist)
                            {
                               bplist.append(bp).append(",");
                            }
                             
      out.write("   \n");
      out.write("                        \n");
      out.write("                             <textarea name=\"bplist\" readonly=\"true\" rows=\"3\" cols=\"25\">");
      out.print(bplist.toString());
      out.write("</textarea>\n");
      out.write("                             <br>\n");
      out.write("\t\t\t<select name=\"symlist\" multiple id=\"words\" style=\"width: 300px\">\n");
      out.write("                        ");

                            int len=IndexServer.listOfSymptoms.size();
                            Iterator iter = IndexServer.listOfSymptoms.iterator();
                            while (iter.hasNext()) 
                            {
                                String val=(String)iter.next();
                                
      out.write("\n");
      out.write("\t\t\t<option name='");
      out.print(val);
      out.write("' value='");
      out.print(val);
      out.write('\'');
      out.write('>');
      out.print(val);
      out.write("</option>\n");
      out.write("                        ");
}
      out.write("\n");
      out.write("\t\t\t</select>\n");
      out.write("                        <br>\n");
      out.write("                       \n");
      out.write("                        <input type=\"submit\" name=\"submit\" value=\"Show Results\">\n");
      out.write("                    </form>\n");
      out.write("\t\t</div>\n");
      out.write("      \n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
