/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2014-04-16 18:23:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Iterator;
import majorserver.IndexServer;

public final class system_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./cssimages/style.css\" />\n");
      out.write("<script src=\"./cssimages/jquery-1.8.0.min.js\"></script>\n");
      out.write("<script src=\"./cssimages/jquery-1.11.0.min.js\"></script>\n");
      out.write("<script src=\"./cssimages/select2.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"./cssimages/select2.css\">\n");
      out.write("\n");
      out.write("<title>Health Diagnosing System</title>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("   \n");
      out.write("    $(document).ready(function() { $(\"#bodyparts\").select2({\n");
      out.write("\t\t\t maximumSelectionSize: 5,\n");
      out.write("\t\t\t allowClear: true,\n");
      out.write("\t\t\t placeholder: \"Type a word\"\n");
      out.write("\t\t\t}); \n");
      out.write("\t\t});\n");
      out.write("                \n");
      out.write("function sympage()\n");
      out.write("{\n");
      out.write("        window.location='./symptoms.jsp';\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("function populateOptions(bpname)\n");
      out.write("{\n");
      out.write("    var bodyform = document.getElementById(\"bodyform\");\n");
      out.write("    var cur = document.getElementById(bpname);\n");
      out.write("    if($.contains(bodyform, cur)){ return; }\n");
      out.write("    var bodyselect=document.createElement(\"select\");\n");
      out.write("    bodyselect.name=\"bodyparts\";\n");
      out.write("    bodyselect.id=bpname;\n");
      out.write("    bodyselect.multiple=true;\n");
      out.write("    \n");
      out.write("    var par = document.createElement(\"p\");\n");
      out.write("    var part=bpname;\n");
      out.write("    par.textContent = part;\n");
      out.write("    bodyform.appendChild(par);\n");
      out.write("    \n");
      out.write("    bodyform.appendChild(bodyselect);\n");
      out.write("    \n");
      out.write("    ");
 
        Iterator iter=null;
        
    
      out.write("\n");
      out.write("    switch (bpname)\n");
      out.write("    {\n");
      out.write("        case 'head':\n");
      out.write("        ");

                
                iter = IndexServer.headbodyparts.iterator();
                while (iter.hasNext()) 
                {
                    String val=(String)iter.next();
                    
      out.write("\n");
      out.write("                    var el = document.createElement(\"option\");\n");
      out.write("                    el.textContent = '");
      out.print(val);
      out.write("';\n");
      out.write("                    el.value = '");
      out.print(val);
      out.write("';\n");
      out.write("                    bodyselect.appendChild(el);\n");
      out.write("                    ");
}
      out.write("\n");
      out.write("        break;\n");
      out.write("        \n");
      out.write("        case 'torso':\n");
      out.write("        ");

                
                iter = IndexServer.torsobodyparts.iterator();
                while (iter.hasNext()) 
                {
                    String val=(String)iter.next();
                    
      out.write("\n");
      out.write("                    var el = document.createElement(\"option\");\n");
      out.write("                    el.textContent = '");
      out.print(val);
      out.write("';\n");
      out.write("                    el.value = '");
      out.print(val);
      out.write("';\n");
      out.write("                    bodyselect.appendChild(el);\n");
      out.write("                    ");
}
      out.write("\n");
      out.write("        break;\n");
      out.write("        \n");
      out.write("        case 'arm':\n");
      out.write("        ");

                
                iter = IndexServer.armbodyparts.iterator();
                while (iter.hasNext()) 
                {
                    String val=(String)iter.next();
                    
      out.write("\n");
      out.write("                    var el = document.createElement(\"option\");\n");
      out.write("                    el.textContent = '");
      out.print(val);
      out.write("';\n");
      out.write("                    el.value = '");
      out.print(val);
      out.write("';\n");
      out.write("                    bodyselect.appendChild(el);\n");
      out.write("                    ");
}
      out.write("\n");
      out.write("        break;\n");
      out.write("        \n");
      out.write("        case 'leg':\n");
      out.write("        ");

                
                iter = IndexServer.legbodyparts.iterator();
                while (iter.hasNext()) 
                {
                    String val=(String)iter.next();
                    
      out.write("\n");
      out.write("                    var el = document.createElement(\"option\");\n");
      out.write("                    el.textContent = '");
      out.print(val);
      out.write("';\n");
      out.write("                    el.value = '");
      out.print(val);
      out.write("';\n");
      out.write("                    bodyselect.appendChild(el);\n");
      out.write("                    ");
}
      out.write("\n");
      out.write("        break;\n");
      out.write("        \n");
      out.write("        case 'pelvis':\n");
      out.write("        ");

                
                iter = IndexServer.pelvisbodyparts.iterator();
                while (iter.hasNext()) 
                {
                    String val=(String)iter.next();
                    
      out.write("\n");
      out.write("                    var el = document.createElement(\"option\");\n");
      out.write("                    el.textContent = '");
      out.print(val);
      out.write("';\n");
      out.write("                    el.value = '");
      out.print(val);
      out.write("';\n");
      out.write("                    bodyselect.appendChild(el);\n");
      out.write("                    ");
}
      out.write("\n");
      out.write("        break;\n");
      out.write("        \n");
      out.write("    }\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("$(document).ready(function() { $(\"#words\").select2({\n");
      out.write("\t\t\t maximumSelectionSize: 5,\n");
      out.write("\t\t\t allowClear: true,\n");
      out.write("\t\t\t placeholder: \"Type a word\"\n");
      out.write("\t\t\t}); \n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body >\n");
      out.write("    <div id=\"page\">\n");
      out.write("\t\t\n");
      out.write("        <div id=\"header\">\n");
      out.write("        \t<h1>Health Diagnosing System</h1>\n");
      out.write("                <h2>Ask your online doctor</h2>\n");
      out.write("            \n");
      out.write("\t      </div>\n");
      out.write("\t\t<div id=\"bar\">\n");
      out.write("\t\t    <ul>\n");
      out.write("\t\t        <li><a href=\"./index.html\">Home</a></li>\n");
      out.write("                        <li><a href=\"#\" onmouseover=\"abc();\"> Diagnosing system</a></li>\n");
      out.write("\t\t        <li><a href=\"./index.html\">Contact</a></li>\n");
      out.write("\t\t    </ul>\n");
      out.write("\t      </div>\n");
      out.write("\t\t<div class=\"contentTitle\"><h1>Symptom checker</h1></div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"contentText\" name=\"contentText\" id=\"contentText\">\n");
      out.write("\t\t  <p>Take the first step and see what could be causing your symptoms. </p>\n");
      out.write("\t\t  <p>Please enter the Body part related to your symptom :</p>\n");
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t<p>Click on human body to identify body part</p>\n");
      out.write("\n");
      out.write("                <!--<canvas id=\"myCanvas\"></canvas> -->\n");
      out.write("\t\t<img src=\"./cssimages/A-Picture-Of-A-Human-Body.jpg\" alt=\"HumanBody\" usemap=\"#human\">\n");
      out.write("\n");
      out.write("\t\t<map id=\"human\" name=\"human\" class=\"human\">\n");
      out.write("                  <area shape=\"rect\" coords=\"79,121,171,268\" alt=\"torso\" onClick=\"populateOptions('torso')\">\n");
      out.write("\t\t  <area shape=\"circle\" coords=\"121,53,50\" alt=\"head\" onClick=\"populateOptions('head')\">\n");
      out.write("\t\t  <area shape=\"poly\" coords=\"65,115,75,126,61,230,35,310,38,370,17,339,40,216,47,136,65,115\" alt=\"lefthand\" onClick=\"populateOptions('arm')\" >\n");
      out.write("\t\t  <area shape=\"poly\" coords=\"176,117,194,129,192,177,201,213,226,337,207,368,206,306,172,186,165,127,176,117\" alt=\"righthand\" onClick=\"populateOptions('arm')\" >\n");
      out.write("\t\t  <area shape=\"poly\" coords=\"71,259,120,284,168,259,141,292,120,319,97,295,71,259\" alt=\"pelvis\" onClick=\"populateOptions('pelvis')\">\n");
      out.write("\t\t  <area shape=\"poly\" coords=\"115,323,108,378,96,467,99,517,101,597,93,633,66,629,78,591,58,499,65,499,65,298,115,323\" alt=\"leftleg\" onClick=\"populateOptions('leg')\">\n");
      out.write("\t\t  <area shape=\"poly\" coords=\"177,297,177,412,178,458,183,493,165,595,177,629,146,633,142,595,143,519,146,475,125,326,177,297\" alt=\"rightleg\" onClick=\"populateOptions('leg')\">\n");
      out.write("\t\t</map>\n");
      out.write("\n");
      out.write("                  <div id=\"symp\" style=\" position:relative;height: 800px; width: 400px;float: right;\"> \n");
      out.write("                    <form action=\"symptoms.jsp\" id=\"bodyform\" method=\"post\">\n");
      out.write("                            <p> Please select relevant body part by clicking on image </p>\n");
      out.write("                            <p> Other: </p>\n");
      out.write("                            <select name=\"bodyparts\" multiple id=\"words\" style=\"width: 300px\">\n");
      out.write("                            ");

                            int len=IndexServer.otherbodyparts.size();
                            Iterator iter1 = IndexServer.otherbodyparts.iterator();
                            while (iter1.hasNext()) 
                            {
                                String val=(String)iter1.next();
                                
      out.write("\n");
      out.write("\t\t\t\t<option name='");
      out.print(val);
      out.write("' value='");
      out.print(val);
      out.write('\'');
      out.write('>');
      out.print(val);
      out.write("</option>\n");
      out.write("                        \t");
}
      out.write("\n");
      out.write("                            </select>\n");
      out.write("                            <!--<select name=\"bodyparts\" multiple id=\"bodyparts\">\n");
      out.write("                                <option value=\"Chest\">Chest</option>\n");
      out.write("                                <option value=\"Heart\">Heart</option>\n");
      out.write("                                <option value=\"Liver\">Liver</option>\n");
      out.write("                                <option value=\"Spleen\">Spleen</option>\n");
      out.write("                                <option value=\"Kidney\">Kidney</option>\n");
      out.write("                                <option value=\"Esophagus\">Esophagus</option>\n");
      out.write("                                <option value=\"Stomach\">Stomach</option>\n");
      out.write("                                <option value=\"Pancreas\">Pancreas</option>\n");
      out.write("                                <option value=\"Intestines\">Intestines</option> \n");
      out.write("                            </select>-->\n");
      out.write("                            <input type=\"submit\" id=\"sub\" name=\"submit\" value=\"Next Step\" style=\"position:relative;float:right;\">\n");
      out.write("                            </input>\n");
      out.write("\t\t\t</form>\n");
      out.write("                <!--  <button type=\"button\" onclick=\"sympage()\" style=\"float:right;\">Next</button>-->\n");
      out.write("\t\t</div>\n");
      out.write("    \n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
